# -*- coding: utf-8 -*-
"""Essay_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T6Z14RQQ1eblx38f1dSmjK496PeELA-O
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#main excel
df=pd.read_excel('asia-industry.xlsx')
df=df[(df['year']>=1999) & (df['year']<=2017)].copy()

#loading other files
df_export=pd.read_excel('export % of GDP.xlsx')
df_long= df_export.melt(id_vars=['Country Code', 'Country Name', 'Series Name', 'Variable Name'],
                        var_name='years_raw',
                        value_name='export_gdp_pct')

df_long

# The 'years_raw' column does not contain only numerical year, so we need to extract it.
df_long['year_clean'] = df_long['years_raw'].str.extract('(\d{4})').astype(int)

# Display the updated DataFrame (optional)
df_long.head()

# merging

df_data=pd.merge(df,df_long,
                 left_on=['countrycode','year'],
                 right_on=['Country Code','year_clean'],
                 how='left'
                 )

df_pop = pd.read_excel('total population.xlsx')

# Melt
df_pop_long = df_pop.melt(id_vars=['Country Code'], var_name='year_raw', value_name='pop_total')


df_pop_long['year_clean'] = df_pop_long['year_raw'].str.extract('(\d{4})')


df_pop_long = df_pop_long.dropna(subset=['year_clean'])

df_pop_long['year'] = df_pop_long['year_clean'].astype(int)



df_gdp = pd.read_excel('GDP per Capital PPP (2021 constant international $).xlsx')

df_gdp_long = df_gdp.melt(id_vars=['Country Code'], var_name='year_raw', value_name='gdp_pcap_ppp')

df_gdp_long['year_clean'] = df_gdp_long['year_raw'].str.extract('(\d{4})')

df_gdp_long = df_gdp_long.dropna(subset=['year_clean'])

df_gdp_long['year'] = df_gdp_long['year_clean'].astype(int)

# Merge population into our growing df_data
df_pop_long = df_pop_long.rename(columns={'Country Code': 'countrycode'})

df_dataF = pd.merge(df_data,
                  df_pop_long,
                  on=['countrycode', 'year'],
                  how='left'
                 )


# Merge GDP
df_gdp_long = df_gdp_long.rename(columns={'Country Code': 'countrycode'})

df_data_final = pd.merge(df_dataF,
                  df_gdp_long,
                  on=['countrycode', 'year'],
                  how='left'
                 )

df_data_final

df_data_final.to_csv('df_data_final', index=False)
print("Merged dataset saved to 'df_merged.csv'")

df_data_final.to_excel('df_data_final.xlsx', index=False)
print("Merged dataset saved to 'df_data_final.xlsx'")

# Creating LAG space
df_data_final['USA_lag']= df_data_final.groupby('countrycode')['usa_imp_sa'].shift(1)

# now cleanning
cols= ['country', 'countrycode', 'year','month',
       'cpi_yoy_nsa','USA_lag',	'exchnage_rate_vs_usd',	'ind_prod_const_sa',	'usa_imp_sa', 'Country Code',	'Country Name', 'gdp_pcap_ppp','pop_total','export_gdp_pct']

df_dataset= df_data_final[cols]
df_dataset= df_dataset.dropna(subset=['USA_lag'])
df_dataset.head()

# Creating log transformations
df_dataset['log_ind_prod_sa']=np.log(df_dataset['ind_prod_const_sa'])
df_dataset['log_usa_imp']= np.log(df_dataset['USA_lag'])

# EDA

df_dataset.info()
df
df_dataset.isnull().sum()
df_dataset.describe()

# Adding a detailed summary here
eda_summary= df_dataset.describe().T
eda_summary

# Checking the mean and median for verification

# Convert 'gdp_pcap_ppp' and 'pop_total' to numeric, coercing errors
df_dataset['gdp_pcap_ppp'] = pd.to_numeric(df_dataset['gdp_pcap_ppp'], errors='coerce')
df_dataset['pop_total'] = pd.to_numeric(df_dataset['pop_total'], errors='coerce')


# Checking median
eda_summary['median'] = df_dataset.median(numeric_only=True)
# Checking variance
eda_summary['variance']= df_dataset.var(numeric_only= True)

#taking out specifics
print(eda_summary[['mean', 'median', 'std', 'variance', 'min', 'max']])

#Creating a global value chain to check which country is more sensitive to US demands
df_dataset['gvc_integration']= df_dataset['log_usa_imp'] * df_dataset['export_gdp_pct']
vars_to_check=['exchnage_rate_vs_usd', 'ind_prod_const_sa', 'export_gdp_pct', 'gvc_integration','usa_imp_sa']


# now checking the skewness
skewness= df_dataset[vars_to_check].skew()
print(skewness)

#plotting
for var in vars_to_check:
  plt.figure(figsize=(10,6))
  sns.histplot(df_dataset[var], kde=True, bins=30, color= 'red')
  plt.title(f'Distribution of {var}')
  plt.xlabel(var)
  plt.ylabel('Frequency')
  plt.show()
  #

# logging
df_dataset['log_exchnage_rate_vs_usd']= np.log(df_dataset['exchnage_rate_vs_usd'])
df_dataset['log_ind_prod_const_sa']= np.log(df_dataset['ind_prod_const_sa'])
df_dataset['log_export_gdp_pct']= np.log(df_dataset['export_gdp_pct'])
df_dataset['log_gvc_integration']= np.log(df_dataset['gvc_integration'])

# Checking Cluster robust standard error

import statsmodels.formula.api as smf
model_f= "log_ind_prod_sa ~ log_usa_imp + log_exchnage_rate_vs_usd + log_export_gdp_pct + log_gvc_integration "

# Checking the models
cluster_r= smf.ols(model_f, data= df_dataset).fit(
    cov_type='cluster',
    cov_kwds={'groups': df_dataset['countrycode']}
)
print(cluster_r.summary())



# The box plot
plt.figure(figsize=(10,6))
sns.boxplot(x= 'countrycode', y= 'ind_prod_const_sa', data=df_dataset)
plt.title('Production distribution per country')
plt.xlabel('Country with country code')
plt.ylabel('Production capabilities')
plt.show()

# The box plot
plt.figure(figsize=(10,6))
sns.boxplot(x= 'countrycode', y= 'log_ind_prod_sa', data=df_dataset)
plt.title('Production distribution per country')
plt.xlabel('Country with country code')
plt.ylabel('Production capabilities')
plt.show()

# Normality test to check the curve only in plot
plt.figure(figsize=(10,6))
sns.histplot(df_dataset['ind_prod_const_sa'], kde=True, bins=30)
plt.title('Production distribution')
plt.xlabel('Production capabilities')
plt.ylabel('Frequency')
plt.show()

# Normality test to check the curve only in plot
plt.figure(figsize=(10,6))
sns.histplot(df_dataset['log_ind_prod_sa'], kde=True, bins=30)
plt.title('Production distribution')
plt.xlabel('Production capabilities')
plt.ylabel('Frequency')
plt.show()

#checking for correlation
correlation_f= df_dataset[['cpi_yoy_nsa','USA_lag','exchnage_rate_vs_usd','ind_prod_const_sa']].corr()
correlation_f

#heatmap
plt.figure(figsize=(10,6))
sns.heatmap(correlation_f, annot= True, cmap='coolwarm')
plt.title('Showing dependencies')
plt.show()

# Creating correlation log variables to check the changes and how much it is affected post filtering all outliers

correlation_log= df_dataset[['cpi_yoy_nsa','exchnage_rate_vs_usd', 'export_gdp_pct', 'log_ind_prod_sa', 'log_usa_imp']].corr()
correlation_log

# creating heatmap
plt.figure(figsize=(10,6))
sns.heatmap(correlation_log, annot= True, cmap='coolwarm')
plt.title('Showing Correlation')
plt.show()

# Creating a scatter plot to show the relationship between the production capacity of asia vs the USA lag

plt.figure(figsize=(10,6))
sns.regplot(x= 'USA_lag', y='ind_prod_const_sa', data= df_dataset, scatter_kws={'alpha':0.3}, line_kws={'color': 'red'})
plt.title('Production vs USA lag with Regression Line')
plt.xlabel('USA lag')
plt.ylabel('Production capabilities')
plt.show()

# Creating a scatter plot to show the relationship between the production capacity of asia vs the USA lag post using log

plt.figure(figsize=(10,6))
sns.regplot(x= 'log_usa_imp', y='log_ind_prod_sa', data= df_dataset, scatter_kws={'alpha':0.3}, line_kws={'color': 'red'})
plt.title('Production vs USA lag with Regression Line- With log')
plt.xlabel('USA lag')
plt.ylabel('Production capabilities')
plt.show()

#Checking the elasticity

plt.figure(figsize=(10,6))
sns.regplot(x='log_exchnage_rate_vs_usd', y='log_ind_prod_sa', data=df_dataset, line_kws={'color': 'red'}, scatter_kws={'alpha':0.2} )
plt.show()

#the tend shows a upward slope but not steep making it inelastic although the dependency is in place

"""While the scatter plot shows a "rise," it cannot handle "Ceteris Paribus" (holding other things constant).

Continuing the OLS method as it will give the elasticity number by omitting the outlers.

Hypothesis Testing:
The objective is clear for the assignment, we need to analyze whether the production scenario increases in Asian market when there is an excessive need or demand in US economy.

Null Hypothesis, *Ho* : There is no relation between the two economies neiher of the scenario affects the market.
Alternate Hypothesis, *H1* : States that yes there is a significant relation between the two economies as if the demand increases in US economy the production capacity will increase in Asian market as they need to produce more to export.

Here we will be using two variables:
Dependent variable(Y) will be Asian Market Industrial production index Seasonally adjusted ~ ***'ind_prod_const_sa'***
Independent variable is US Imports which is lagged by a month of time as shipping is a factor here ~ ***USA_lag***
"""

# Create country dummies
country_dummies = pd.get_dummies(df_dataset['countrycode'], drop_first=True).astype(int)

# combining log variable, dummie and interaction
X= pd.concat([df_dataset[['log_usa_imp','gvc_integration','cpi_yoy_nsa','exchnage_rate_vs_usd']], country_dummies], axis=1)

# Hypothesis testing
import statsmodels.formula.api as sm
import statsmodels.api as sm_api # Import statsmodels.api

X = sm_api.add_constant(X)
y = df_dataset['log_ind_prod_sa']
X = X.apply(pd.to_numeric, errors='coerce')

# run the model
model = sm_api.OLS(endog=y, exog=X).fit()
print(model.summary())

import statsmodels.api as sm
countries= ['MYS', 'PHL', 'SGP', 'THA']
individual_results = {}

for c in countries:
  c_data= df_dataset[df_dataset['countrycode']==c].dropna()

  Y= c_data['log_ind_prod_sa']
  X= c_data[['log_exchnage_rate_vs_usd','log_export_gdp_pct','log_gvc_integration']]
  X= sm.add_constant(X)
  model= sm.OLS(endog=Y, exog=X).fit()
  individual_results[c]= model
  print(f'Results for {c}:')

  print(model.summary())

# Individual plotting for each state
state= sns.FacetGrid(df_dataset, col='countrycode', col_wrap=2, height=4, sharey=False)
state.map(sns.regplot, 'log_usa_imp', 'log_ind_prod_sa', scatter_kws={'alpha':0.3}, line_kws={'color': 'red'})
state.set_axis_labels('Log US import demand', 'Log Industrial Production')
state.set_titles(col_template="{col_name}")
plt.savefig('Regression_slopes')

"""Hypothesis Test"""

# Crearting hypothesis test using pearsonr and spearmanr

import scipy.stats as stats

df_data_clean= df_dataset[['log_usa_imp', 'log_ind_prod_sa']].dropna()

# Pearsonr
r_coeff,p_vals= stats.pearsonr(df_data_clean['log_usa_imp'], df_data_clean['log_ind_prod_sa'])
print(f'Pearson Correlation Coefficient: {r_coeff}')
print(f'P-value: {p_vals}')

# Spearmanr
r_coeff,p_vals= stats.spearmanr(df_data_clean['log_usa_imp'], df_data_clean['log_ind_prod_sa'])
print(f'Spearmanr Correlation Coefficient: {r_coeff}')
print(f'P-value: {p_vals}')

import scipy.stats as stats

# Defining Timeline

era1= df_dataset[(df_dataset['year']>=1997) & (df_dataset['year']<=2007)].dropna(subset=['log_usa_imp','log_ind_prod_sa'])
era2= df_dataset[(df_dataset['year']>=2010) & (df_dataset['year']<=2017)].dropna(subset=['log_usa_imp','log_ind_prod_sa'])

# Hypothesis check paired T test

# For era1- BEFORE CRISIS
t_pair1, p_pair1= stats.ttest_rel(era1['log_usa_imp'],era1['log_ind_prod_sa'])

# For era2- AFTER CRISIS
t_pair2, p_pair2= stats.ttest_rel(era2['log_usa_imp'],era2['log_ind_prod_sa'])

print(f"Paired T test values are:")
print(f"Pair1: t-stats:{t_pair1}, p-value:{p_pair1}")
print(f"Pair2: t-stats:{t_pair2}, p-value:{p_pair2}")

# Independent T test Hypothesis

t_ind, p_ind= stats.ttest_ind(era1['log_ind_prod_sa'],era2['log_ind_prod_sa'])

print(f"Independent T test values are:")
print(f"Independent_era1: t-stats:{t_ind}, p-value:{p_ind}")

# The quality check using Shapiro Wilk Test to check the curve and check the normality

p_curve1= stats.shapiro(era1['log_ind_prod_sa']).pvalue
p_curve2= stats.shapiro(era2['log_ind_prod_sa']).pvalue

print(f"Normality test values are:")
print(f"Curve1: p-value:{p_curve1:.3f}")
print(f"Curve2: p-value:{p_curve2:.3f}")

